CLASS zcl_lab_11_system_dnavas DEFINITION
  PUBLIC
  CREATE PUBLIC .
  PUBLIC SECTION.

  data ARCHITECTURE type string VALUE '64BITS'.

 METHODS GET_ARCHITECTURE RETURNING VALUE(R_VALUE) TYPE STRING.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_lab_11_system_dnavas IMPLEMENTATION.
  METHOD get_architecture.
    r_value = ME->architecture.
  ENDMETHOD.
ENDCLASS.
