CLASS zcl_lab_12_linux_dnavas DEFINITION INHERITING FROM zcl_lab_11_SYSTEM_dnavas
  PUBLIC
  FINAL
  CREATE PUBLIC .
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_lab_12_linux_dnavas IMPLEMENTATION.
ENDCLASS.
